name: CMake cross-platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install dependencies
        run: sudo apt install -y libglew-dev libglfw3 cmake
      - name: Run cmake configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build release version
        run: cmake --build build

  build-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run cmake configure
        run: cmake -B build -S .
      - name: Build release version
        run: cmake --build build --config Release
      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: Executable and dlls
          path: |
            build/Release/GL3H.dll
            build/Release/glew32.dll
            build/Release/glfw3.dll
            build/Release/GraRen.dll
            build/Release/PongPlusPlus.exe